# IS 4487 Lab 2

## Outline

- Loading installed packages
- Inspect data
- Explore plot types

<a href="https://colab.research.google.com/github/Stan-Pugsley/is_4487_base/blob/main/Labs/Scripts/lab2_megatelco_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Load Libraries

In this class we will be using
- Pandas
- Scikitlearn
- Matplotlib

In [14]:
import pandas as pd
import matplotlib as mpl
import sklearn as sl

## Getting data into Pandas
See the Canvas assignments and lectures for a description of the Megatelco data

In [15]:
df = pd.read_csv('https://github.com/Stan-Pugsley/is_4487_base/blob/main/Labs/DataSets/megatelco_leave_survey.csv?raw=true')
print (df)

     college  income  overage  leftover   house  handset_price  \
0        one   23859       70         0  519105            154
1       zero   72466       67        16  271182            262
2       zero   30883       60         0  647281            211
3        one   44512        0        22  754958            232
4       zero   70535        0         0  653421            310
...      ...     ...      ...       ...     ...            ...
4995    zero   93699       26        56  385632            384
4996    zero   25806       67        87  691020            142
4997     one   97033      138        28  710559            311
4998    zero   91558      229        15  853464            379
4999     one  115943      200        42  173038            459

      over_15mins_calls_per_month  average_call_duration  \
0                             5.0                      8
1                             5.0                      5
2                             3.0                      8
3                             0.0                      5
4                             0.0                     14
...                           ...                    ...
4995                          5.0                      1
4996                          4.0                      2
4997                         10.0                      2
4998                         27.0                      4
4999                         24.0                      2

     reported_satisfaction reported_usage_level considering_change_of_plan  \
0                      low                  low                        yes
1                      low                  low                        yes
2                      low                  low                        yes
3                      low                  low                         no
4                      low                  low                        yes
...                    ...                  ...                        ...
4995                  high                  low                        yes
4996                  high                  low                         no
4997                   low                 high                        yes
4998                  high                  low                         no
4999                  high                 high                        yes

      leave     id
0     LEAVE   8183
1     LEAVE  12501
2      STAY   7425
3     LEAVE  13488
4      STAY  11389
...     ...    ...
4995  LEAVE  19270
4996   STAY  14549
4997   STAY   9972
4998   STAY  12685
4999  LEAVE  13561

[5000 rows x 13 columns]

In [16]:
#look at the top rows
df.head(10)

,college,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,reported_satisfaction,reported_usage_level,considering_change_of_plan,leave,id
0,one,23859,70,0,519105,154,5.0,8,low,low,yes,LEAVE,8183
1,zero,72466,67,16,271182,262,5.0,5,low,low,yes,LEAVE,12501
2,zero,30883,60,0,647281,211,3.0,8,low,low,yes,STAY,7425
3,one,44512,0,22,754958,232,0.0,5,low,low,no,LEAVE,13488
4,zero,70535,0,0,653421,310,0.0,14,low,low,yes,STAY,11389
5,zero,143987,0,56,896544,778,5.0,1,low,high,yes,STAY,14674
6,one,96668,79,24,259329,365,5.0,6,low,avg,yes,LEAVE,19100
7,one,50083,0,0,160335,266,5.0,10,low,high,yes,STAY,18170
8,one,104392,0,0,247836,778,1.0,8,high,low,no,LEAVE,3201
9,one,37852,0,74,264893,857,0.0,2,low,low,yes,LEAVE,12612

In [17]:
#look at last rows
df.tail(10)

,college,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,reported_satisfaction,reported_usage_level,considering_change_of_plan,leave,id
4990,one,158179,226,21,269368,478,18.0,5,avg,high,yes,LEAVE,18481
4991,one,75711,47,0,519512,326,4.0,12,high,high,yes,STAY,9790
4992,one,34039,59,0,541872,165,3.0,10,low,high,yes,STAY,19985
4993,zero,88713,0,70,587559,319,0.0,2,low,low,yes,LEAVE,17220
4994,zero,123820,0,71,608639,888,1.0,2,low,high,yes,STAY,10396
4995,zero,93699,26,56,385632,384,5.0,1,high,low,yes,LEAVE,19270
4996,zero,25806,67,87,691020,142,4.0,2,high,low,no,STAY,14549
4997,one,97033,138,28,710559,311,10.0,2,low,high,yes,STAY,9972
4998,zero,91558,229,15,853464,379,27.0,4,high,low,no,STAY,12685
4999,one,115943,200,42,173038,459,24.0,2,high,high,yes,LEAVE,13561

In [18]:
#get a summary of the dataset
df.describe()

,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,id
count,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03,4997.000000,5000.000000,5000.000000
mean,79912.948400,85.119200,24.243600,493656.326600,7.876236e+02,7.744647,5.958800,10036.639400
std,41703.042384,85.655622,26.847496,254287.193865,2.828291e+04,8.806070,4.390417,5813.620304
min,-28811.000000,0.000000,0.000000,-796132.000000,1.300000e+02,0.000000,1.000000,2.000000
25%,41592.500000,0.000000,0.000000,260586.500000,2.190000e+02,1.000000,2.000000,4950.500000
50%,75041.500000,59.000000,15.000000,451865.500000,3.220000e+02,4.000000,5.000000,10126.000000
75%,115475.000000,177.000000,42.000000,701608.750000,5.280000e+02,14.000000,9.000000,15085.250000
max,159938.000000,335.000000,89.000000,1000000.000000,2.000234e+06,29.000000,15.000000,20000.000000

In [19]:
#look at the datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   college                      5000 non-null   object
 1   income                       5000 non-null   int64
 2   overage                      5000 non-null   int64
 3   leftover                     5000 non-null   int64
 4   house                        5000 non-null   int64
 5   handset_price                5000 non-null   int64
 6   over_15mins_calls_per_month  4997 non-null   float64
 7   average_call_duration        5000 non-null   int64
 8   reported_satisfaction        5000 non-null   object
 9   reported_usage_level         5000 non-null   object
 10  considering_change_of_plan   5000 non-null   object
 11  leave                        5000 non-null   object
 12  id                           5000 non-null   int64
dtypes: float64(1), int64(7), object(5)
memory usage: 507.9+ KB

## Selecting Specific Columns
Square bracket subsetting, or indexing, is a way to access specific rows and columns of a DataFrame. When you use square brackets, [], with a DataFrame you can pass in:

A single column name to select a single column (returns a Series)
A list of column names to select multiple columns (returns a DataFrame)
A boolean mask to select rows based on a condition
A slice to select a range of rows
For example, df['college'] selects the college column as a Series, while df[['college', 'income']] selects the college and income columns as a DataFrame.

In [20]:
df['college']

0        one
1       zero
2       zero
3        one
4       zero
        ...
4995    zero
4996    zero
4997     one
4998    zero
4999     one
Name: college, Length: 5000, dtype: object

In [21]:
df[['college', 'income']]

     college  income
0        one   23859
1       zero   72466
2       zero   30883
3        one   44512
4       zero   70535
...      ...     ...
4995    zero   93699
4996    zero   25806
4997     one   97033
4998    zero   91558
4999     one  115943

[5000 rows x 2 columns]

## Filtering Rows
You create a boolean mask by applying a logical condition to a DataFrame, which returns True/False values. You can then use this mask to select the rows where the condition is True.

In [22]:
df["handset_price"] > 1000

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Name: handset_price, Length: 5000, dtype: bool

## Clean up the data
Did you notice anything unusual about the "house" amounts?

How about the handset price and income?

In [23]:
df_clean = df[(df['house'] > 0) & (df['income'] > 0) & (df['handset_price'] < 1000)]
df_clean.describe()

,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,id
count,4997.000000,4997.000000,4997.000000,4997.000000,4997.000000,4994.000000,4997.000000,4997.000000
mean,79918.829498,85.116270,24.247549,494019.823294,387.558935,7.739287,5.957174,10034.365619
std,41673.392025,85.638266,26.848091,253648.357473,213.614256,8.802897,4.388938,5814.189195
min,20028.000000,0.000000,0.000000,150305.000000,130.000000,0.000000,1.000000,2.000000
25%,41593.000000,0.000000,0.000000,260729.000000,219.000000,1.000000,2.000000,4949.000000
50%,75026.000000,59.000000,15.000000,452277.000000,322.000000,4.000000,5.000000,10125.000000
75%,115464.000000,177.000000,42.000000,701614.000000,528.000000,14.000000,9.000000,15084.000000
max,159938.000000,335.000000,89.000000,1000000.000000,899.000000,29.000000,15.000000,20000.000000

# Add Derived Attribute

Add a column with the income in K (thousands)

In [24]:
df_clean['income_k'] = (df_clean['income']/1000).round(2)
df_clean.head()

<ipython-input-24-41bea05a8bf4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['income_k'] = (df_clean['income']/1000).round(2)

,college,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,reported_satisfaction,reported_usage_level,considering_change_of_plan,leave,id,income_k
0,one,23859,70,0,519105,154,5.0,8,low,low,yes,LEAVE,8183,23.86
1,zero,72466,67,16,271182,262,5.0,5,low,low,yes,LEAVE,12501,72.47
2,zero,30883,60,0,647281,211,3.0,8,low,low,yes,STAY,7425,30.88
3,one,44512,0,22,754958,232,0.0,5,low,low,no,LEAVE,13488,44.51
4,zero,70535,0,0,653421,310,0.0,14,low,low,yes,STAY,11389,70.54

## Summarize the Data
 What is average house price at the two levels of leave?

 Conclusion?  Stayers have substantially more expensive homes.

In [25]:
df_clean[['house','leave']].groupby('leave').mean().round(2)

           house
leave
LEAVE  439255.26
STAY   547591.97

In [37]:
df_clean['reported_satisfaction'].value_counts()

reported_satisfaction
low     2999
high    1530
avg      465
Name: count, dtype: int64

In [34]:
df_clean['considering_change_of_plan'].value_counts()

considering_change_of_plan
yes      3230
no       1488
maybe     276
Name: count, dtype: int64

## Additional Data Preparation

➡️ Assignment Tasks
- Add at least two additional steps to clean or filter the dataset

In [39]:
# Drop rows with NULL values
df_clean.dropna(inplace = True)

# Target potential churn subjects
df_clean = df_clean[(df_clean['reported_satisfaction'] != 'high') & (df_clean['considering_change_of_plan'] != 'no')]
df_clean.describe()

,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,id,income_k
count,2458.000000,2458.000000,2458.000000,2458.000000,2458.000000,2458.000000,2458.000000,2458.000000,2458.000000
mean,80331.304719,86.136290,24.936941,500043.791294,390.268104,7.710334,5.906428,10089.729455,80.331265
std,41724.340098,85.741833,27.062547,255217.440194,216.599751,8.738031,4.396713,5868.693280,41.724378
min,20045.000000,0.000000,0.000000,150305.000000,130.000000,0.000000,1.000000,2.000000,20.050000
25%,41462.750000,0.000000,0.000000,266320.500000,217.000000,1.000000,2.000000,4873.500000,41.465000
50%,76326.500000,60.000000,16.000000,454618.000000,322.500000,4.000000,5.000000,10215.000000,76.325000
75%,115550.000000,178.000000,43.000000,710921.500000,530.750000,14.000000,9.000000,15185.500000,115.547500
max,159938.000000,301.000000,89.000000,999758.000000,899.000000,29.000000,15.000000,19997.000000,159.940000

## Data Visualization

➡️ Assignment Tasks
- Add at least two charts to show a summary of any major trends